# Generated by Django 4.2.6 on 2023-10-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(help_text='Enter 10 digits phone number', max_length=10, verbose_name='Phone Number'),
        ),
    ]
